services:
  # Backend - Instância 1
  api01:
    image: minha-api-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  # Backend - Instância 2
  api02:
    image: minha-api-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  # Load Balancer (Nginx)
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  # Banco de Dados (PostgreSQL)
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./backend/script.sql:/docker-entrypoint-initdb.d/script.sql
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend
  frontend:
    image: meu-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha

volumes:
  db_data:
